// PATH: services/api/src/providers/llm/prompts/topics.ts
// WHAT: Prompt template for weekly topic suggestions
// WHY:  Keeps topic output practical and SMB-oriented
// RELEVANT: services/api/src/providers/llm/contracts.ts,services/api/src/core/topics.ts

export const TOPICS_SUGGEST_SYSTEM = [
  'You are EditorialDesk planning a weekly SMB blog topic slate.',
  'Suggest practical, safe, high-signal topics aligned to listed experts.',
  'Do not invent company facts. Use only provided context.',
  'Output valid JSON only.',
].join('\n');

export const TOPICS_SUGGEST_USER = [
  'Create weekly topic plan for:',
  'Company: {{company_name}}',
  'Domain: {{company_domain}}',
  'Experts JSON: {{experts_json}}',
  '',
  'Return JSON:',
  '{',
  '  "topics": [',
  '    {',
  '      "title": "...",',
  '      "description": "...",',
  '      "source_type": "faq|myth|seasonal|service",',
  '      "expert_id": "optional"',
  '    }',
  '  ]',
  '}',
  'Provide 6-10 topics, practical and actionable.',
].join('\n');

export const CONTENT_STRATEGY_12W_SYSTEM = [
  'You are EditorialDesk strategy planner for SMB editorial teams.',
  'Build a practical 12-week content strategy, not abstract SEO theory.',
  'Use only provided context. Do not invent business facts.',
  'Output valid JSON only.',
].join('\n');

export const CONTENT_STRATEGY_12W_USER = [
  'Build structured 12-week strategy plan for:',
  'Topic seed: {{topic_seed}}',
  'Expert name: {{expert_name}}',
  'Audience: {{audience}}',
  'Market: {{market}}',
  'Constraints JSON: {{constraints_json}}',
  '',
  'Return JSON with this shape:',
  '{',
  '  "horizon_weeks": 12,',
  '  "pillars": [',
  '    {',
  '      "pillar_id": "p1",',
  '      "title": "...",',
  '      "goal": "...",',
  '      "clusters": [',
  '        {',
  '          "item_id": "c1",',
  '          "week": 1,',
  '          "title": "...",',
  '          "angle": "...",',
  '          "target_keyword": "...",',
  '          "interlink_to": ["f1"],',
  '          "copy_payload": {',
  '            "title": "...",',
  '            "description": "...",',
  '            "source_type": "service",',
  '            "expert_id": "optional"',
  '          }',
  '        }',
  '      ],',
  '      "faq": [',
  '        {',
  '          "item_id": "f1",',
  '          "week": 1,',
  '          "question": "...",',
  '          "short_answer": "...",',
  '          "interlink_to": ["c1"],',
  '          "copy_payload": {',
  '            "title": "...",',
  '            "description": "...",',
  '            "source_type": "faq",',
  '            "expert_id": "optional"',
  '          }',
  '        }',
  '      ]',
  '    }',
  '  ],',
  '  "interlinking": [',
  '    { "from_item_id": "c1", "to_item_id": "f1", "anchor_hint": "..." }',
  '  ]',
  '}',
  'Rules: weeks 1..12 only, no empty titles, keep plan actionable.',
].join('\n');
